spring:
  application:
    name: banking-service
#
#  datasource:
#    url: jdbc:mariadb://localhost:3306/haen_payment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: sa
#    password: 1234
#
#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      #      hbm2ddl:
#      #        auto: create
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true

#service:
#  membership:
#    url: localhost:8081